In [81]:
import pandas as pd

In [82]:
df = pd.read_csv('vacancys_final.csv')

In [83]:
df.head(10)

,Unnamed: 0,id,title,category,company,format,level,salary,link,skills
0,0,36700,quality assurance (manual),qa,NDA,удалённо по РФ,senior,от 240 000 ₽,https://hirehi.ru/qa/quality-assurance-manual-...,"['qa', 'manual testing', 'test automation', 'a..."
1,1,36699,iOS разработчик,development,Экосистема тенниса,удалённо,senior,от 350 000 ₽,https://hirehi.ru/development/ios-razrabotchik...,"['swift', 'uikit', 'xcode', 'storyboard', 'gcd..."
2,2,36697,platform engineer,devops,NDA,удалённо,senior,~ 372 000 ₽,https://hirehi.ru/devops/platform-engineer-36697,"['gardenlinux', 'linux', 'kvm', 'qemu', 'libvi..."
3,3,36696,growth marketing manager,marketing,NDA,удалённо,middle,~ 223 000 ₽,https://hirehi.ru/marketing/growth-marketing-m...,"['monetization', 'ltv', 'ab testing', 'b2c', '..."
4,4,36695,Бизнес аналитик,analytics,ВТБ,гибрид Москва,middle,~ 210 000 ₽,https://hirehi.ru/analytics/biznes-analitik-36695,"['аналитика', 'бизнес-планирование', 'экономик..."
5,5,36694,DevOps инженер,devops,Сбер,гибрид Москва,senior,~ 345 000 ₽,https://hirehi.ru/devops/devops-inzhener-36694,"['devops', 'kubernetes', 'helm', 'ansible', 'c..."
6,6,36693,Python Developer,development,Сбер,гибрид Н.Новгород,middle,от 90 000 ₽,https://hirehi.ru/development/python-developer...,"['prompt engineering', 'llm', 'rag', 'python',..."
7,7,36692,c++ developer,development,Level 26 Games,удалённо,senior,от 320 000 ₽,https://hirehi.ru/development/c-developer-36692,"['c++', 'unreal engine', 'ios', 'android', 'no..."
8,8,36691,Аналитик данных,analytics,Магнит,гибрид Москва,intern,~ 65 000 ₽,https://hirehi.ru/analytics/analitik-dannyh-36691,"['sql', 'excel', 'анализ данных', 'отчетность'..."
9,9,36690,Системный аналитик,analytics,МТС,удалённо по РФ,senior,~ 282 000 ₽,https://hirehi.ru/analytics/sistemnyi-analitik...,"['системный анализ', 'микросервисы', 'highload..."

In [84]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8754 entries, 0 to 8753
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8754 non-null   int64
 1   id          8754 non-null   int64
 2   title       8754 non-null   str
 3   category    8754 non-null   str
 4   company     8754 non-null   str
 5   format      8754 non-null   str
 6   level       8754 non-null   str
 7   salary      8708 non-null   str
 8   link        8754 non-null   str
 9   skills      8754 non-null   str
dtypes: int64(2), str(8)
memory usage: 684.0 KB

In [85]:
df['category'].unique()

<StringArray>
['qa', 'development', 'devops', 'marketing', 'analytics', 'management',
 'design']
Length: 7, dtype: str

In [86]:
test = df[['title', 'category']]
test.head(10)

                        title     category
0  quality assurance (manual)           qa
1             iOS разработчик  development
2           platform engineer       devops
3    growth marketing manager    marketing
4             Бизнес аналитик    analytics
5              DevOps инженер       devops
6            Python Developer  development
7               c++ developer  development
8             Аналитик данных    analytics
9          Системный аналитик    analytics

In [87]:
test = test.sample(100, random_state=42)

In [88]:
test.head()

                    title     category
3150    системный инженер       devops
5050   системный аналитик    analytics
8211       .net developer  development
7595  qa инженер (manual)           qa
994    frontend developer  development

In [89]:
import requests

r = requests.get('http://127.0.0.1:1234/api/v1/models')
print(r.json())

{'models': [{'type': 'llm', 'publisher': 'qwen', 'key': 'qwen/qwen3-vl-8b', 'display_name': 'Qwen3 VL 8B', 'architecture': 'qwen3_vl', 'quantization': {'name': '4bit', 'bits_per_weight': 4}, 'size_bytes': 5776816177, 'params_string': '8B', 'loaded_instances': [{'id': 'qwen/qwen3-vl-8b', 'config': {'context_length': 4096}}], 'max_context_length': 262144, 'format': 'mlx', 'capabilities': {'vision': True, 'trained_for_tool_use': True}, 'description': None, 'variants': ['qwen/qwen3-vl-8b@4bit'], 'selected_variant': 'qwen/qwen3-vl-8b@4bit'}, {'type': 'embedding', 'publisher': 'nomic-ai', 'key': 'text-embedding-nomic-embed-text-v1.5', 'display_name': 'Nomic Embed Text v1.5', 'quantization': {'name': 'Q4_K_M', 'bits_per_weight': 4}, 'size_bytes': 84106624, 'params_string': None, 'loaded_instances': [], 'max_context_length': 2048, 'format': 'gguf'}]}

In [90]:
headers = {
    'Content-Type': 'application/json',
    'Authorization': 'Bearer ***'
}
system_prompt ='You must answer in json format to user question.'
data = {
    'model': 'qwen/qwen3-vl-8b',
    'input': 'Say hello world',
    'system_prompt': system_prompt,
}
r = requests.post('http://127.0.0.1:1234/api/v1/chat', headers=headers, json=data)
print(r.json())

{'model_instance_id': 'qwen/qwen3-vl-8b', 'output': [{'type': 'message', 'content': '{\n  "message": "Hello, World!"\n}'}], 'stats': {'input_tokens': 26, 'total_output_tokens': 12, 'reasoning_output_tokens': 0, 'tokens_per_second': 36.27360275344213, 'time_to_first_token_seconds': 5.192}, 'response_id': 'resp_f71e59df649630e6c5b07a316a41386b29ae257c7cc1bf42'}

In [91]:
prompt_header1 = '''
You are a job title classification assistant.

Task:
Assign each vacancy title to exactly one category from the allowed list.

Allowed categories:
- qa
- development
- devops
- marketing
- analytics
- management
- design

Rules:
- Choose exactly one category per title.
- Do not invent new categories.
- Focus on the core job function.
- Ignore seniority words such as Junior, Middle, Senior, Lead, Head.
- Ignore company names, location, remote/hybrid markers, emojis, and salary mentions.
- If a title is ambiguous, choose the closest category based on the main function.
- If the title is too vague to classify reliably, use Other.

Responce format:
[{"id": 1, "category": "development"}, {"id": 2, "category": "marketing"}, ...]

## Job Titles to Classify:
'''
def cook_promt(objects, prompt_header):
    prompt = prompt_header
    for i, obj in enumerate(objects):
        prompt += f"{i+1}. {obj}\n"
    return prompt
prompt = cook_promt(test['title'].tolist(), prompt_header1)
prompt

'\nYou are a job title classification assistant.\n\nTask:\nAssign each vacancy title to exactly one category from the allowed list.\n\nAllowed categories:\n- qa\n- development\n- devops\n- marketing\n- analytics\n- management\n- design\n\nRules:\n- Choose exactly one category per title.\n- Do not invent new categories.\n- Focus on the core job function.\n- Ignore seniority words such as Junior, Middle, Senior, Lead, Head.\n- Ignore company names, location, remote/hybrid markers, emojis, and salary mentions.\n- If a title is ambiguous, choose the closest category based on the main function.\n- If the title is too vague to classify reliably, use Other.\n\nResponce format:\n[{"id": 1, "category": "development"}, {"id": 2, "category": "marketing"}, ...]\n\n## Job Titles to Classify:\n1. системный инженер\n2. системный аналитик\n3. .net developer\n4. qa инженер (manual)\n5. frontend developer\n6. product manager\n7. Golang Developer\n8. c++ разработчик\n9. mobile developer\n10. sre engineer\n11. c++ developer\n12. qa инженер (auto)\n13. Дата аналитик\n14. product manager\n15. System Analyst\n16. Backend разработчик\n17. графический дизайнер\n18. Product Owner\n19. product designer\n20. Инженер данных\n21. product manager\n22. devops engineer\n23. ai разработчик\n24. Java разработчик\n25. automation qa\n26. node.js developer\n27. java developer\n28. affiliate manager\n29. python developer\n30. data engineer\n31. react native developer\n32. kotlin developer\n33. growth marketing manager\n34. devops engineer\n35. SMM Specialist\n36. devops engineer\n37. angular developer\n38. программист 1с\n39. data engineer\n40. data analyst\n41. Data Analyst\n42. разработчик 1c\n43. Product Manager\n44. UX/UI Designer\n45. ручной тестировщик\n46. automation qa\n47. product manager\n48. golang разработчик\n49. fullstack developer\n50. smm-специалист\n51. C++ Developer\n52. разработчик платформы данных\n53. php разработчик\n54. владелец продукта\n55. ios developer\n56. qa engineer (manual)\n57. Менеджер проектов\n58. automation qa\n59. ux/ui дизайнер\n60. automation qa\n61. автоматизатор тестирования\n62. системный инженер\n63. Product Analyst\n64. аналитик данных\n65. Python разработчик\n66. react native разработчик\n67. бизнес аналитик\n68. Дата аналитик\n69. DevOps Engineer\n70. продакт-менеджер\n71. Golang разработчик\n72. python разработчик\n73. Менеджер продукта\n74. веб-дизайнер\n75. Дата аналитик\n76. бэкенд разработчик\n77. Data Analyst\n78. Frontend разработчик\n79. affiliate manager\n80. sre engineer\n81. руководитель продукта\n82. Android разработчик\n83. head of creative\n84. go developer\n85. project manager\n86. python developer\n87. ux/ui дизайнер\n88. data analyst\n89. продакт-менеджер\n90. Product Manager\n91. Product Owner (tech)\n92. mlops engineer\n93. qa инженер (manual)\n94. Системный аналитик\n95. mlops engineer\n96. manual qa\n97. бизнес аналитик\n98. business analyst\n99. ML Engineer\n100. ml engineer\n'

In [92]:
def send_request(prompt):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***'
    }
    system_prompt ='You must answer in json format to user question.'
    data = {
        'model': 'qwen/qwen3-vl-8b',
        'input': prompt,
        'system_prompt': system_prompt,
    }
    r = requests.post('http://127.0.0.1:1234/api/v1/chat', headers=headers, json=data)
    return r

In [93]:
p = cook_promt(test['title'].head(10).tolist(), prompt_header1)
response = send_request(p)
print(response.json())

{'model_instance_id': 'qwen/qwen3-vl-8b', 'output': [{'type': 'message', 'content': '[{"id": 1, "category": "devops"}, {"id": 2, "category": "analytics"}, {"id": 3, "category": "development"}, {"id": 4, "category": "qa"}, {"id": 5, "category": "development"}, {"id": 6, "category": "management"}, {"id": 7, "category": "development"}, {"id": 8, "category": "development"}, {"id": 9, "category": "development"}, {"id": 10, "category": "devops"}]'}], 'stats': {'input_tokens': 267, 'total_output_tokens': 126, 'reasoning_output_tokens': 0, 'tokens_per_second': 32.63686718948077, 'time_to_first_token_seconds': 4.602}, 'response_id': 'resp_b00ead2ef6a25958bfb7b52bc00cf7fb34c5efe91e317c3e'}

In [94]:
import json
answer = response.json()
answer = answer['output']
answer = answer[0]['content']
answer = json.loads(answer)
answer, type(answer)
for i in answer:
    print(i['id'], i['category'])

1 devops
2 analytics
3 development
4 qa
5 development
6 management
7 development
8 development
9 development
10 devops

In [95]:
import json
import time

def cook_promt(objects, prompt_header):
    prompt = prompt_header
    for i in objects:
        prompt += f"{i['id']}. {i['title']}\n"
    return prompt


def send_request(prompt):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***'
    }
    system_prompt ='You must answer in json format to user question.'
    data = {
        'model': 'qwen/qwen3-vl-8b',
        'input': prompt,
        'system_prompt': system_prompt,
    }
    r = requests.post('http://127.0.0.1:1234/api/v1/chat', headers=headers, json=data)
    return r


def predict(df, batch_size=10):
    new_df = df.copy()
    titles = [{'id': i, 'title': df['title'].iloc[i]} for i in range(len(df))]
    batches = [titles[i:i+batch_size] for i in range(0, len(titles), batch_size)]
    new_df['predict_category'] = None
    for batch in batches:
        try:
            prompt = cook_promt(batch, prompt_header1)
            answer = send_request(prompt)
            answer = answer.json()
            answer = answer['output']
            answer = answer[0]['content']
            answer = json.loads(answer)
            indexes = [i['id'] for i in batch]
            for i in range(len(indexes)):
                if indexes[i] == answer[i]['id']:
                    new_df.loc[indexes[i], 'predict_category'] = answer[i]['category']
        except Exception as e:
            print(f'Error on batch{batch}')
    return new_df



test = test.reset_index(drop=True)
d = predict(test)

In [96]:

test.index

RangeIndex(start=0, stop=100, step=1)

In [97]:
d.head(20)

                   title     category predict_category
0      системный инженер       devops           devops
1     системный аналитик    analytics        analytics
2         .net developer  development      development
3    qa инженер (manual)           qa               qa
4     frontend developer  development      development
5        product manager   management       management
6       Golang Developer  development      development
7        c++ разработчик  development      development
8       mobile developer  development      development
9           sre engineer       devops           devops
10         c++ developer  development      development
11     qa инженер (auto)           qa               qa
12         Дата аналитик    analytics        analytics
13       product manager   management       management
14        System Analyst    analytics       management
15   Backend разработчик  development      development
16  графический дизайнер       design           design
17         Product Owner   management       management
18      product designer       design           design
19        Инженер данных  development        analytics

In [98]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(d['category'], d['predict_category'])
print(accuracy)

0.94

In [99]:
test = test.reset_index(drop=True)
d = predict(test,batch_size=100)
accuracy = accuracy_score(d['category'], d['predict_category'])
print(accuracy)

0.91

Крч размер батча не роляет

In [100]:
d.head()

                 title     category predict_category
0    системный инженер       devops           devops
1   системный аналитик    analytics        analytics
2       .net developer  development      development
3  qa инженер (manual)           qa               qa
4   frontend developer  development      development