In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

В этом ноутбуке формируется дополнительная таблица skills.
- Строка таблицы - `id` вакансии и соответствующий навык `skill`
- Связь с вакансиями из исходной таблицы осуществляется через `id`

In [181]:
data = pd.read_csv('vacancys_final.csv')
data.sample(3)

,Unnamed: 0,id,title,category,company,format,level,salary,link,skills
5418,5418,30459,fullstack developer,development,GB Agency,удалённо,senior,~ от 430 000 ₽,https://hirehi.ru/development/fullstack-develo...,"['python', 'sql', 'javascript', 'django', 'typ..."
2398,2398,34161,devops engineer,devops,NDA,удалённо,senior,~ от 482 100 ₽,https://hirehi.ru/devops/devops-engineer-34161,"['devops', 'sre', 'terraform', 'pulumi', 'clou..."
558,558,36133,fullstack developer,development,TrueSpace,удалённо,middle,~ 186 000 ₽,https://hirehi.ru/development/fullstack-develo...,"['ai', 'redis', 'docker', 'typescript', 'webso..."

In [172]:
data['skills'].value_counts()

skills
[]                                                                                                                                                                            55
['typescript', 'react', 'angular', 'git', 'linux', 'mvvm', 'fsd', 'ci/cd', 'тестирование', 'архитектура']                                                                      2
['java', 'devops', 'linux', 'docker', 'kubernetes', 'kafka', 'opensearch', 'postgres']                                                                                         2
['java', 'spring', 'hibernate', 'gradle', 'jms', 'jax-ws', 'junit', 'confluence', 'jira', 'agile', 'devops', 'micro-frontend', 'ios', 'android']                               2
['golang', 'docker', 'postgres', 'rabbitmq', 'kafka', 'grpc', 'rest api', 'grafana', 'prometheus', 'agile', 'nomad', 'consul', 'jaeger', 'opensearch', 'sentry']               2
                                                                                                                                                                              ..
['1с', '1с erp', '1с ка', '1с ут', 'управляемые формы', 'git', 'бсп', 'rmq']                                                                                                   1
['bpmn', 'er', 'sequence diagram', 'use case', 'activity', 'sql', 'nosql', 'iot', 'scada', 'mlops', 'bigdata', 'bi', 'dwh']                                                    1
['linux', 'kvm', 'proxmox', 'vmware', 'zfs', 'nas', 'vlan', 'vpn', 'wireguard', 'dns', 'dhcp', 'firewalls', 'sso', 'mfa', 'rbac', 'ansible', 'bash', 'python']                 1
['react.js', 'nodejs', 'express', 'typescript', 'mongodb', 'sql', 'clickhouse', 'api', 'websocket', 'kafka', 'mqtt', 'react native', 'remix', 'tanstack query', 'zustand']     1
['product vision', 'roadmap', 'backlog', 'b2b', 'cloud', 'kubernetes', 'cni', 'networking', 'iaas', 'paas', 'backend', 'metrics', 'delivery']                                  1
Name: count, Length: 8671, dtype: int64

Данные в колонке представлены строковым типом. для дальнейшей обработки преобразуем в массив с помощью функции:

In [173]:
data['skills'].sample(3)

3230    ['manual testing', 'automation testing', 'api ...
2630    ['продуктовая аналитика', 'анализ поведения', ...
3038    ['swift', 'uikit', 'swiftui', 'alamofire', 'ur...
Name: skills, dtype: object

In [182]:
def str_to_list(skills_string):
    try: 
        if not skills_string or skills_string == "[]":
            return []
        skills_string = skills_string[1:-1].split(",")
        skills_list = [skill.replace("'", "").strip() for skill in skills_string]
        return skills_list
    except Exception:
        return []

Для формирования дополнительного столбца используется метод [`explode`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html):

In [183]:
data["skills"] = data["skills"].apply(lambda x: str_to_list(x))

In [184]:
data_skills = data[["id", "skills"]].explode("skills").rename(columns={'skills': 'skill'})
data_skills

         id            skill
0     36700               qa
0     36700   manual testing
0     36700  test automation
0     36700              api
0     36700             sdlc
...     ...              ...
8753  24786       prometheus
8753  24786           docker
8753  24786       kubernetes
8753  24786            nginx
8753  24786       postgresql

[102907 rows x 2 columns]

In [177]:
data_skills.to_csv("skills.csv", index=False)