In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

В этом ноутбуке формируется дополнительная таблица skills.
- Строка таблицы - `id` вакансии и соответствующий навык `skill`
- Связь с вакансиями из исходной таблицы осуществляется через `id`

In [4]:
data = pd.read_csv("vacancys_final.csv")
data.sample(3)

,Unnamed: 0,id,title,category,company,format,level,salary,link,skills
7315,7315,27625,automation qa,qa,Plata Card,удалённо,middle,зп не указана,https://hirehi.ru/qa/automation-qa-27625,"['qa', 'testing', 'backend testing', 'ui testi..."
3899,3899,32389,java developer,development,Unlimit,офис Белград,senior,~ от 453 000 ₽,https://hirehi.ru/development/java-developer-3...,"['java', 'kotlin', 'spring boot', 'llm', 'rag'..."
5629,5629,30134,Full Stack Developer,development,Yandex Cloud,гибрид Москва,senior,~ от 342 300 ₽,https://hirehi.ru/development/full-stack-devel...,"['nodejs', 'react', 'typescript', 'postgresql'..."

In [188]:
data["skills"].value_counts()

skills
[]                                                                                                                                                                            55
['typescript', 'react', 'angular', 'git', 'linux', 'mvvm', 'fsd', 'ci/cd', 'тестирование', 'архитектура']                                                                      2
['java', 'devops', 'linux', 'docker', 'kubernetes', 'kafka', 'opensearch', 'postgres']                                                                                         2
['java', 'spring', 'hibernate', 'gradle', 'jms', 'jax-ws', 'junit', 'confluence', 'jira', 'agile', 'devops', 'micro-frontend', 'ios', 'android']                               2
['golang', 'docker', 'postgres', 'rabbitmq', 'kafka', 'grpc', 'rest api', 'grafana', 'prometheus', 'agile', 'nomad', 'consul', 'jaeger', 'opensearch', 'sentry']               2
                                                                                                                                                                              ..
['1с', '1с erp', '1с ка', '1с ут', 'управляемые формы', 'git', 'бсп', 'rmq']                                                                                                   1
['bpmn', 'er', 'sequence diagram', 'use case', 'activity', 'sql', 'nosql', 'iot', 'scada', 'mlops', 'bigdata', 'bi', 'dwh']                                                    1
['linux', 'kvm', 'proxmox', 'vmware', 'zfs', 'nas', 'vlan', 'vpn', 'wireguard', 'dns', 'dhcp', 'firewalls', 'sso', 'mfa', 'rbac', 'ansible', 'bash', 'python']                 1
['react.js', 'nodejs', 'express', 'typescript', 'mongodb', 'sql', 'clickhouse', 'api', 'websocket', 'kafka', 'mqtt', 'react native', 'remix', 'tanstack query', 'zustand']     1
['product vision', 'roadmap', 'backlog', 'b2b', 'cloud', 'kubernetes', 'cni', 'networking', 'iaas', 'paas', 'backend', 'metrics', 'delivery']                                  1
Name: count, Length: 8671, dtype: int64

Данные в колонке представлены строковым типом. для дальнейшей обработки преобразуем в массив с помощью функции:

In [189]:
data["skills"].sample(3)

494     ['дизайн', 'графика', 'графический дизайн', 'г...
8088    ['python', 'docker', 'ml', 'mlops', 'elt', 'ci...
5118    ['flutter', 'api testing', 'postman', 'swagger...
Name: skills, dtype: object

In [5]:
def str_to_list(skills_string):

    try:
        if not skills_string or skills_string == "[]":
            return []
        skills_string = skills_string[1:-1].split(",")
        skills_list = [
            skill.replace("'", "").strip().lower() for skill in skills_string
        ]
        skills_list = set(skills_list)
        return list(skills_list)

    except Exception:
        return []

Для формирования дополнительного столбца используется метод [`explode`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.explode.html):

In [6]:
data["skills"] = data["skills"].apply(lambda x: str_to_list(x))

In [7]:
data_skills = (
    data[["id", "skills"]].explode("skills").rename(columns={"skills": "skill"})
)
data_skills

         id               skill
0     36700         web testing
0     36700         test design
0     36700  test documentation
0     36700         qa strategy
0     36700  process management
...     ...                 ...
8753  24786          postgresql
8753  24786          kubernetes
8753  24786            teamcity
8753  24786              gitlab
8753  24786             grafana

[102907 rows x 2 columns]

In [193]:
data_skills.to_csv("skills.csv", index=False)