In [1]:
import pandas as pd
df = pd.read_csv('vacancies_cleaned.csv')

In [4]:
df.head(2)

,title,link,tags,company,skills,salary,relocation,employment_type,onsite,remote,hybrid,lead,c_level,senior,director,trainee,head,middle,junior,location
0,Account Executive (SaaS),https://hirify.me/jobs/440679-account-executiv...,"['hybrid', 'US', 'fulltime', 'middle']",Company hidden,"['crm', 'sales', 'negotiation', 'saas', 'healt...",64 000 - 74 000\n$,False,fulltime,True,True,False,False,False,False,False,False,False,True,False,US
1,"Senior Account Manager, Key Accounts (SaaS)",https://hirify.me/jobs/440678-senior-account-m...,"['onsite', 'US', 'fulltime', 'senior']",Company hidden,"['sales', 'account management', 'salesforce', ...",NaN,False,fulltime,False,True,True,False,False,True,False,False,False,False,False,US

In [10]:
test = df[['title', 'location']]

In [11]:
test.head()

                                         title   location
0                     Account Executive (SaaS)         US
1  Senior Account Manager, Key Accounts (SaaS)         US
2      Forward-Deployed Data Scientist II (AI)  Australia
3             Customer Support Specialist (AI)  Australia
4  Deal Strategy And Pricing Manager (Fintech)      Italy

In [8]:
prompt_header1 = '''
You are a job title classification assistant.

Task:
Assign each vacancy title to exactly one category from the allowed list.

Allowed categories:
- qa
- development
- devops
- marketing
- analytics
- management
- design

Rules:
- Choose exactly one category per title.
- Do not invent new categories.
- Focus on the core job function.
- Ignore seniority words such as Junior, Middle, Senior, Lead, Head.
- Ignore company names, location, remote/hybrid markers, emojis, and salary mentions.
- If a title is ambiguous, choose the closest category based on the main function.
- If the title is too vague to classify reliably, use Other.

Responce format:
[{"id": 1, "category": "development"}, {"id": 2, "category": "marketing"}, ...]

## Job Titles to Classify:
'''
def cook_promt(objects, prompt_header):
    prompt = prompt_header
    for i, obj in enumerate(objects):
        prompt += f"{i+1}. {obj}\n"
    return prompt

In [15]:
import json
import time
import requests

def cook_promt(objects, prompt_header):
    prompt = prompt_header
    for i in objects:
        prompt += f"{i['id']}. {i['title']}\n"
    return prompt


def send_request(prompt):
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ***'
    }
    system_prompt ='You must answer in json format to user question.'
    data = {
        'model': 'qwen/qwen3-vl-8b',
        'input': prompt,
        'system_prompt': system_prompt,
    }
    r = requests.post('http://127.0.0.1:1234/api/v1/chat', headers=headers, json=data)
    return r


def predict(df, batch_size=10):
    new_df = df.copy()
    titles = [{'id': i, 'title': df['title'].iloc[i]} for i in range(len(df))]
    batches = [titles[i:i+batch_size] for i in range(0, len(titles), batch_size)]
    new_df['predict_category'] = None
    for batch in batches:
        print(f'Batch: {batch[0]['id']}')
        try:
            prompt = cook_promt(batch, prompt_header1)
            answer = send_request(prompt)
            answer = answer.json()
            answer = answer['output']
            answer = answer[0]['content']
            answer = json.loads(answer)
            indexes = [i['id'] for i in batch]
            for i in range(len(indexes)):
                if indexes[i] == answer[i]['id']:
                    new_df.loc[indexes[i], 'predict_category'] = answer[i]['category']
        except Exception as e:
            print(f'Error on batch{batch}')
    return new_df



test = test.reset_index(drop=True)
d = predict(test, 150)

Batch: 0
Batch: 150
Batch: 300
Batch: 450
Batch: 600
Batch: 750
Batch: 900
Batch: 1050
Batch: 1200
Batch: 1350
Batch: 1500
Batch: 1650
Batch: 1800
Batch: 1950
Batch: 2100
Batch: 2250
Batch: 2400
Batch: 2550
Batch: 2700
Batch: 2850
Batch: 3000
Batch: 3150
Batch: 3300
Batch: 3450
Batch: 3600
Batch: 3750
Batch: 3900
Batch: 4050
Batch: 4200
Batch: 4350
Batch: 4500
Batch: 4650
Batch: 4800
Batch: 4950
Batch: 5100
Batch: 5250
Batch: 5400
Batch: 5550
Batch: 5700
Batch: 5850
Batch: 6000
Batch: 6150
Batch: 6300
Batch: 6450
Batch: 6600
Batch: 6750
Batch: 6900
Batch: 7050
Batch: 7200
Batch: 7350
Batch: 7500
Batch: 7650
Batch: 7800
Batch: 7950
Batch: 8100
Batch: 8250
Batch: 8400
Batch: 8550
Batch: 8700
Batch: 8850
Batch: 9000
Batch: 9150
Batch: 9300
Batch: 9450
Batch: 9600
Batch: 9750
Batch: 9900
Error on batch[{'id': 9900, 'title': 'Директор по МСФО'}, {'id': 9901, 'title': 'VIP Account Manager (Marketing)'}, {'id': 9902, 'title': 'Ассистент по комментингу (Маркетинг)'}, {'id': 9903, 'title': 'Lead Motion Editor (VFX)'}, {'id': 9904, 'title': 'Customer Program Manager (AI)'}, {'id': 9905, 'title': 'Head of Product (Fintech)'}, {'id': 9906, 'title': 'Senior DevOps Engineer (AI)'}, {'id': 9907, 'title': 'Senior Security Consultant (DevSecOps)'}, {'id': 9908, 'title': 'Data Scientist (Igaming)'}, {'id': 9909, 'title': 'React/React Native Developer'}, {'id': 9910, 'title': 'Motion Editor (GameDev)'}, {'id': 9911, 'title': '2D FX Animator (Gamedev)'}, {'id': 9912, 'title': 'Junior Implementation Consultant (Fintech)'}, {'id': 9913, 'title': 'Gen-AI Producer (AI)'}, {'id': 9914, 'title': 'Product Marketing Manager'}, {'id': 9915, 'title': 'Project Director'}, {'id': 9916, 'title': 'UI/UX Designer'}, {'id': 9917, 'title': 'Programmatic Executive (AdTech)'}, {'id': 9918, 'title': 'Product Manager (AI)'}, {'id': 9919, 'title': 'Network Engineer'}, {'id': 9920, 'title': 'Senior Fullstack Java Developer (Insurance)'}, {'id': 9921, 'title': 'Benefit Operations Analyst'}, {'id': 9922, 'title': 'SDET (Python)'}, {'id': 9923, 'title': 'Директолог (Медиа)'}, {'id': 9924, 'title': 'Ведущий аналитик 1С (Oracle E-Business Suite)'}, {'id': 9925, 'title': 'Solution Architect (Java)'}, {'id': 9926, 'title': 'Ведущий программист 1С'}, {'id': 9927, 'title': 'Senior In-App Media Buyer (Gambling)'}, {'id': 9928, 'title': 'Middle Manual QA Engineer (Edtech)'}, {'id': 9929, 'title': 'Data Engineer (Analytics Engineer)'}, {'id': 9930, 'title': 'Junior Affiliate Manager (iGaming)'}, {'id': 9931, 'title': 'Менеджер по продажам (Эзотерика)'}, {'id': 9932, 'title': 'Sales Development Representative (Cybersecurity)'}, {'id': 9933, 'title': 'Специалист службы поддержки'}, {'id': 9934, 'title': 'Senior Legal & Compliance Manager'}, {'id': 9935, 'title': 'Коммерческий директор'}, {'id': 9936, 'title': 'Менеджер по работе с проектными институтами (Прескриптор)'}, {'id': 9937, 'title': 'Retention Agent (Forex)'}, {'id': 9938, 'title': 'Senior Director, Global Tech Partnerships'}, {'id': 9939, 'title': 'Junior Backend Developer (AI)'}, {'id': 9940, 'title': 'Стажер-маркетолог'}, {'id': 9941, 'title': 'Procurement Operations Analyst'}, {'id': 9942, 'title': 'Senior iOS Developer'}, {'id': 9943, 'title': 'UI/UX Designer'}, {'id': 9944, 'title': 'Finance Manager (Real Estate)'}, {'id': 9945, 'title': 'Content Manager'}, {'id': 9946, 'title': 'Координатор культурных проектов'}, {'id': 9947, 'title': 'Configuration Specialist (Software)'}, {'id': 9948, 'title': 'UX/UI Дизайнер'}, {'id': 9949, 'title': 'VIP Account Manager (iGaming)'}, {'id': 9950, 'title': 'Accountant/Accounting Manager (Fintech)'}, {'id': 9951, 'title': 'Team Lead, Customer Care (Fintech)'}, {'id': 9952, 'title': 'QA Automation Engineer (Python)'}, {'id': 9953, 'title': 'Редактор экспертного контента (Marketing)'}, {'id': 9954, 'title': 'Senior Embedded Linux Developer (Embedded Systems)'}, {'id': 9955, 'title': 'Digital Performance Lead (AI)'}, {'id': 9956, 'title': 'Embedded Video/Streaming Architect (Embedded Systems)'}, {'id': 9957, 'title': 'Planning Executive'}, {'id': 9958, 'title': 'Head Of Customer Experience'}, {'id': 9959, 'title': 'Senior System Analyst'}, {'id': 9960, 'title': 'Java Developer (Summer Practice)'}, {'id': 9961, 'title': 'Автор текста'}, {'id': 9962, 'title': 'Summer Practice Student (Java)'}, {'id': 9963, 'title': 'Project Manager (Marketing)'}, {'id': 9964, 'title': 'Senior Digital Design Engineer (Automotive)'}, {'id': 9965, 'title': 'Strategic Sales Account Manager (Robotics)'}, {'id': 9966, 'title': 'Director Of Product Marketing (AI)'}, {'id': 9967, 'title': 'Senior Java-разработчик'}, {'id': 9968, 'title': 'Principal Digital Design Engineer (Automotive)'}, {'id': 9969, 'title': 'Commercial Director (Investment Projects)'}, {'id': 9970, 'title': 'CRM Campaign Manager (Ecommerce)'}, {'id': 9971, 'title': 'Системный аналитик (Kafka/REST API)'}, {'id': 9972, 'title': 'Learning and Development Business Partner (Fintech)'}, {'id': 9973, 'title': 'Amazon Account Manager'}, {'id': 9974, 'title': 'Director Of Product Marketing (AI)'}, {'id': 9975, 'title': 'Senior Fullstack Engineer (AI)'}, {'id': 9976, 'title': 'Senior Fullstack Developer (Python)'}, {'id': 9977, 'title': 'Digital Wholesale Intern (Fashion)'}, {'id': 9978, 'title': 'Tech Lead Business Lending (Fintech)'}, {'id': 9979, 'title': 'Senior Frontend Engineer (React)'}, {'id': 9980, 'title': 'Backend Developer (Fintech)'}, {'id': 9981, 'title': 'Junior DevOps Engineer'}, {'id': 9982, 'title': 'Директор производства'}, {'id': 9983, 'title': 'MarTech & Ops Lead (Iterable)'}, {'id': 9984, 'title': 'International Tax Analyst (Fintech)'}, {'id': 9985, 'title': 'Channel Marketing Localization Manager'}, {'id': 9986, 'title': 'Frontend Developer (Vue)'}, {'id': 9987, 'title': 'Contracts Manager (SaaS)'}, {'id': 9988, 'title': 'Revenue Enablement Manager (SaaS)'}, {'id': 9989, 'title': 'Senior Business Value Engineer (SaaS)'}, {'id': 9990, 'title': 'Tech Talent Acquisition Lead (SaaS)'}, {'id': 9991, 'title': 'Senior Frontend Developer (Fintech)'}, {'id': 9992, 'title': 'Gameplay AI Programmer (Gamedev)'}, {'id': 9993, 'title': 'Sound Design Intern (Gamedev)'}, {'id': 9994, 'title': 'Technical Sound Designer (Gamedev)'}, {'id': 9995, 'title': 'Account Executive (Semi Government)'}, {'id': 9996, 'title': 'Associate Account Executive (Sales)'}, {'id': 9997, 'title': 'Senior Growth Manager (B2C)'}, {'id': 9998, 'title': 'Senior React Developer'}, {'id': 9999, 'title': 'Solution Architect'}, {'id': 10000, 'title': 'Team Lead Business Solutions (Fintech)'}, {'id': 10001, 'title': 'Sr. SLED Account Executive (Networking)'}, {'id': 10002, 'title': 'Cybersecurity Program Manager'}, {'id': 10003, 'title': 'Middle QA Engineer (iGaming)'}, {'id': 10004, 'title': 'Архитектор информационной безопасности'}, {'id': 10005, 'title': 'DevOps Engineer (Data Platform)'}, {'id': 10006, 'title': 'HR Generalist'}, {'id': 10007, 'title': 'Commercial Manager (Cybersecurity)'}, {'id': 10008, 'title': 'Middle+/Senior QA Engineer (Backend)'}, {'id': 10009, 'title': 'Финансовый директор (CFO)'}, {'id': 10010, 'title': 'SMM-специалист'}, {'id': 10011, 'title': 'Middle Product Owner (iGaming)'}, {'id': 10012, 'title': 'Senior 3D Motion Designer'}, {'id': 10013, 'title': 'Staff Senior Golang Engineer (Backend)'}, {'id': 10014, 'title': 'Director Of Compliance (AI)'}, {'id': 10015, 'title': 'AI Visual/Cinematic Creator'}, {'id': 10016, 'title': 'Account Management Executive (Fintech)'}, {'id': 10017, 'title': 'Staff Senior PHP Backend Engineer (Laravel)'}, {'id': 10018, 'title': 'Senior Client Account Executive (Mid-Market)'}, {'id': 10019, 'title': 'Senior Business Manager (Key Accounts)'}, {'id': 10020, 'title': 'Specialist, Product Strategy (Fintech)'}, {'id': 10021, 'title': 'Customer Relationship Manager (Sales)'}, {'id': 10022, 'title': 'Коммерческий директор (Агрохолдинг)'}, {'id': 10023, 'title': 'Senior Infrastructure Planning and Cabling Engineer'}, {'id': 10024, 'title': 'IT Incubator Participant (AI)'}, {'id': 10025, 'title': 'Recruiter (HR)'}, {'id': 10026, 'title': 'IC Agentic Engineering Manager (AI)'}, {'id': 10027, 'title': 'Middle / Senior Product Analyst (Yandex Maps)'}, {'id': 10028, 'title': 'Стажер Менеджер Продукта (1С)'}, {'id': 10029, 'title': 'Директор департамента закупок'}, {'id': 10030, 'title': 'Middle DevOps Engineer (AWS)'}, {'id': 10031, 'title': 'Senior Data Engineer (GCP)'}, {'id': 10032, 'title': 'Senior Fullstack Developer (PHP)'}, {'id': 10033, 'title': 'Technical Interviewer (Business/System Analyst)'}, {'id': 10034, 'title': '3D Character Artist'}, {'id': 10035, 'title': 'UI/UX Lead (Gamedev)'}, {'id': 10036, 'title': 'Project Manager (Bitrix24)'}, {'id': 10037, 'title': 'Senior Data Engineer (Databricks)'}, {'id': 10038, 'title': 'Sales Development Coordinator (Fintech)'}, {'id': 10039, 'title': 'Backend Developer (Scala)'}, {'id': 10040, 'title': 'Старший менеджер по развитию рекламных агентств'}, {'id': 10041, 'title': 'Контент-менеджер / SMM'}, {'id': 10042, 'title': 'Директор по стратегическому маркетингу'}, {'id': 10043, 'title': 'Senior Data Analyst'}, {'id': 10044, 'title': 'UI/UX & AI Designer'}, {'id': 10045, 'title': 'Senior .NET Backend Developer'}, {'id': 10046, 'title': 'Marketing Project Manager'}, {'id': 10047, 'title': 'Программист микроконтроллеров'}, {'id': 10048, 'title': '3D Motion Designer (Unreal Engine)'}, {'id': 10049, 'title': 'Системный аналитик (1С-Битрикс)'}]
Batch: 10050
Batch: 10200
Batch: 10350
Batch: 10500

In [16]:
d.head(10)
d.to_csv('predicted.csv')

In [18]:
d['predict_category'].value_counts()

predict_category
management          3381
development         2972
marketing           1548
analytics            834
design               693
devops               395
qa                   345
Other                151
other                104
sales                 69
customer support      28
security              27
customer service       3
education              2
Name: count, dtype: int64